spring.application.name=Project-3-springboot


server.port=8089


# View Resolver configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Static resources configuration
spring.mvc.static-path-pattern=/static/**