spring.application.name=Project-3-springboot

server.port=8089

# View Resolver configuration
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Static resources configuration
spring.mvc.static-path-pattern=/static/**


sitemesh.integration=view-resolver
sitemesh.decorator.prefix=/decorators/
sitemesh.decorator.default=web.jsp
sitemesh.dispatchMode=include


spring.datasource.url=jdbc:mysql://localhost:3306/project3
spring.datasource.username=root
spring.datasource.password=MYSQL####1e1510
spring.jpa.hibernate.ddl-auto=update



server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true